### ISSUE TITLE
Determine minimal work for first release

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS-Game#48]
So that it's clear what needs to be done, and after that it's just a box-ticking exercise.

* [x] Auto-build & publish .exe on Windows. #43 #49 #51.
* [x] Auto-build & Publish Linux .tar.bz2. #70.
* ~~Auto-build & Publish Ubuntu .deb. #36.~~
* [x] Figure out how to build on Mac OS X. #45.
* [x] Publish Mac .dmg.
* [x] Publish Mac .dmg to GitHub. #84.
* [x] Auto deploy server continuously. #62. #57.
* [x] Test non-authenticated version. #72.
* [x] Integrate ActionFPS.com authentication fully. #58. User logs in, loads key, joins server.
* [x] actionfps:// url from ActionFPS to load properly on Linux #80.
* [x] Set up actionfps:// url in Linux. #86.
* [x] Verify actionfps:// url from works full stack on Windows. #82.
* [x] Verify OS X build works. #81
* [x] Verify OS X auth works. #85
* ~~Test a few games with users.~~

**Comment by ScalaWilliam** [comment]
#84 complete.

All achieved, closing.

**Comment by lucasgautheron** [comment]
:clap:
